<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tr>
                <th style="background-image:url('graf/linia1.jpg')"></th>
                <th scope="col">
                    <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                </th>
                <th style="background-image:url('graf/linia1.jpg')"></th>
            </tr>
            <tr>
                <th width="40%" scope="col"></th>
                <th width="800" scope="col">
                    <div align="left">
                        <img src="graf/osrodek1.jpg" width="397" height="28" align="top" />
                    </div>
                </th>
                <th width="40%" scope="col"></th>
            </tr>
        </table>
        <table class="content" align="center" >
            <tr>
                <td class="styl24 top-left-menu">
                    <img src="graf/start1.gif" alt="Start" class="start-gif" />
                    <ul class="styl42">
                        <li><a href="index.phtml">główna</a></li>
                        <li><a href="buddyzm.phtml">buddyzm</a></li>
                        <li><a href="wydarzenia.phtml">aktualności</a></li>
                        <li><a href="kontakt.phtml">kontakt</a></li>
                        <li><a href="linki.phtml">linki</a></li>
                    </ul>
                </td>
                <td rowspan="2" class="center-field">
                    <div class="styl43">
                        <h2 align="center">Wprowadzenie do Buddyzmu</h2>
                        <div align="justify">
                            <p>Budda miał przed 2550 laty wyjątkowe możliwości nauczania: żyjąc w czasie wspaniałego rozkwitu kultury,
                                otoczony bardzo zdolnymi uczniami, mógł przez czterdzieści pięć lat po osiągnięciu Oświecenia wskazywać
                                innym prowadzące do niego drogę. Dlatego również jego nauki, zwane Dharmą, są tak różnorodne i bogate.</p>

                            <p>Kandziur, słowa samego Buddy, składa się ze 108 tomów, zawierających 84000 nauk.
                                Późniejsze komentarze do nich, Tendziur, obejmują dalsze 254 grube księgi.
                                Z tego powodu Budda pod koniec życia powiedział: "Mogę umrzeć szczęśliwy. 
                                Nie zatrzymałem żadnej nauki w zamkniętej dłoni. Dałem wam już wszystko,
                                co mogło przynieść pożytek." Jego ostatnia nauka wyróżnia buddyzm na tle innych religii.</p>

                            <p>Buddyzm jest więc czymś bardzo praktycznym, czymś co można bezpośrednio zastosować w życiu. 
                                Kiedy ludzie pytali Buddę, dlaczego i czego naucza, odpowiadał zawsze tak samo:
                                "Nauczam, ponieważ wy i wszystkie istoty pragniecie osiagnąć szczęście i uniknąć cierpienia.
                                Nauczam, jakimi rzeczy są."<br />
                                Czym jest więc buddyzm? Najlepszym określeniem opisującym nauki Buddy jest to,
                                którego używał on sam. Przez 1500 lat nauki te praktykowane były w Indiach pod nazwą "Dharma",
                                a przez ostatnie tysiąc lat w Tybecie jako "Czio". Oba te wyrażenia oznaczają "jakimi rzeczy są".</p>

                            Zrozumienie tego, jakimi rzeczy są, jest kluczem do trwałej radoś.
                            Sam Budda jest nauczycielem, przykładem, strażnikiem i przyjacielem.
                            Pomaga nam i wszystkim istotom unikać cierpienia i dowiadczać stanów coraz intensywniejszego szczęścia i radości,
                            a także prowadzić innych do Wyzwolenia i Oświecenia.<br />
                            <em>Cytaty z książki Lamy Ole Nydahla "O naturze rzeczy" Wydawnictwo Czarna Owca, 2012</em><br /><br />
                            Zobacz także <a href="medytacja.phtml">medytacja...</a>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <div align="right"> 
                        <a href="http://www.karmapa.pl/16karmapa/index.htm" onmouseover='karmapa.src = "graf/1g.jpg"' 
                           onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                            <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" /></a>

                        <a href="http://www.karmapa.pl/" onmouseover='trinlej.src = "graf/2g.jpg"' 
                           onmouseout='trinlej.src = "graf/2.jpg"' target="_blank"><img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" /></a>

                        <a href="http://www.lama-ole.pl/" onmouseover='ole.src = "graf/3g.jpg"' 
                           onmouseout='ole.src = "graf/3.jpg"' target="_blank"><img name="ole" src="graf/3.jpg" alt="tekst alternatywny" /></a>
                    </div> 
                </td>
            </tr>
        </table>
        <div align="center">
            <hr width="50%"></hr>
            © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
        </div>
    </body>
</html>
