<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tbody>
                <tr>
                    <th style="background-image:url('graf/linia1.jpg')"></th>
                    <th scope="col">
                        <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                    </th>
                    <th style="background-image:url('graf/linia1.jpg')"></th>
                </tr>
                <tr>
                    <th scope="col" width="40%"></th>
                    <th scope="col" width="800">
                        <div align="left">
                            <img src="graf/osrodek1.jpg" align="top" height="28" width="397" />
                        </div>
                    </th>
                    <th scope="col" width="40%"></th>
                </tr>
            </tbody>
        </table>
        <table class="content" align="center">
            <tbody>
                <tr>
                    <td class="top-left-menu styl24">
                        <img src="graf/start1.gif" alt="Start" class="start-gif" />
                        <ul class="styl42">
                            <li><a href="index.phtml">główna</a></li>
                            <li><a href="buddyzm.phtml">buddyzm</a></li>
                            <li><a href="wydarzenia.phtml">aktualności</a></li>
                            <li><a href="kontakt.phtml">kontakt</a></li>
                            <li><a href="linki.phtml">linki</a></li>
                        </ul>
                    </td>
                    <td class="index-main">
                        <img src="graf/buddyzm1.gif" alt="Buddyzm" align="left" height="27" width="70" />
                        <p class="styl43">
                        <br />
                        Kiedy ludzie pytali Buddę, dlaczego i czego naucza, odpowiadał zawsze
                        tak samo: "Nauczam, ponieważ wy i wszystkie istoty pragniecie osiągnąć
                        szczęśćie i uniknąć cierpienia. Nauczam, jakimi rzeczy są."<br />
                        <br />
                        Czym jest zatem buddyzm?... <a href="buddyzm.phtml">&gt;&gt;</a>
                        </p>
                    </td>
                    <td rowspan="2" bgcolor="#fbf397" valign="top" width="219"><img src="graf/medytacje1.gif" alt="Medytacje" /><br />
                        <br />
                        <div class="styl24">
                            <span class="styl30"><strong>Medytacja XVI Karmapy:</strong></span>
                        </div> <br />
                        <div class="styl30">
                            <strong>wtorek - <span class="styl37"> 19:00 </span></strong>
                        </div><br />
                        <div class="styl30">
                            <strong>czwartek - <span class="styl37"> 19:00</span></strong>
                        </div><br />
                        <div class="styl30">
                            <strong>sobota - <span class="styl37"> 19:00 </span></strong>
                        </div><br />
                        <br />
                        <span class="styl45"> Medytacje prowadzone są po
                        polsku i trwają około 30 minut. Nie wymagają żadnych specjalnych
                        przygotowań i każdy nieodpłatnie może wziąć w nich udział.
                        Dodatkowo, we wtorki o godzinie 18:30, można otrzymać
                        wyjaśnienia do medytacji. Zapraszamy :)
                        </span><br />
                        <br />
                        <span class="styl30"><strong>Adres ośrodka:</strong><br />
                        ul. Legionowa 11/132 <br />
                        15-281 Białystok - <a href="mapa.phtml">(mapa)</a>
                        </span><br />
                        <span class="styl30">tel. 503 737 130 / 721 958 121</span><br />
                        <br />
                        <a href="newsletter.php">
                        <span class="styl25" style="font-family: Monotype Corsiva;">&gt;&gt;Newsletter</span>
                        </a>
                    </td>
                </tr>
                <tr>
                   <td rowspan="4" valign="top" >
                    <div align="right">
                        <a href="http://www.karmapa.org/life-16th-karmapa" onmouseover='karmapa.src = "graf/1g.jpg"'
                        onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                        <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" />
                        </a>
                        <a href="http://www.karmapa.org/" onmouseover='trinlej.src = "graf/2g.jpg"'
                        onmouseout='trinlej.src = "graf/2.jpg"' target="_blank">
                        <img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" />
                        </a>
                        <a href="http://www.lama-ole-nydahl.pl/" onmouseover='ole.src = "graf/3g.jpg"'
                        onmouseout='ole.src = "graf/3.jpg"' target="_blank">
                        <img name="ole" src="graf/3.jpg" alt="tekst alternatywny" />
                        </a>
                    </div>
                </td>
                    </td>
                    <td rowspan="2" class="index-main">
                        <img src="graf/medytacja1.gif" alt="Medytacja" align="left" height="27" width="80" />
                        <p class="styl43">
                        <br />
                        Medytacja oznacza w buddyzmie "wolne od wysiłku spoczywanie w tym co jest".
                        Można urzeczywistnić ten stan dzięki uspokojeniu i opanowaniu umysłu, budzącym
                        współczucie i mądrość, lub pracy z wewnętrznymi energiami i
                        formami buddów uczynionymi ze światła.
                        <br />
                        <br />
                        Najskuteczniejsza jest jednak ciagła identyfikacja z własną naturą buddy ... <a href="medytacja.phtml">&gt;&gt;</a>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td rowspan="3" bgcolor="#fbf397" valign="top" width="219">
                        <img src="graf/aktualnosci1.gif" alt="Aktualnosci" /><br />
                        <br />
                        <a href="wydarzenia.phtml">&gt;&gt; Zapraszamy na wykład nauczyciela buddyzmu Tadeusza Uchto<br/>
                        19 lutego (piątek), godz.19.00</a>
                        <br />
                        <br />
                        <a href="http://buddyzm.pl/wydarzenia" target="_blank">&gt;&gt;
                        Wydarzenia w Polsce</a> <br />
                        <br />
                        <a href="http://www.diamondway-buddhism.org/pdf/travelplan.pdf" target="_blank">&gt;&gt;
                        Plan podróży Lamy Ole Nydahla</a> <br />
                        <p><i>Ostatnia aktualizacja 14.02.2016</i></p>
                    </td>
                </tr>
                <tr>
                    <td class="index-main">
                        <img src="graf/osrodek1.gif" alt="Osrodek" align="left" height="27" width="158" />
                        <p class="styl43">
                        <br />
                        Ośrodek medytacyjny w Białymstoku jest jednym z ponad sześćdziesięciu ośrodkow linii
                        Karma Kagyu w Polsce i ponad sześciuset ośrodków na całym świecie. Założył je
                        Lama Ole Nydahl - pierwszy zachodni... <a href="osrodek.phtml">&gt;&gt; </a>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td align="left" bgcolor="#dbdbdb" height="59" valign="top">
                        <div align="center">
                            <strong>"Nie ma drogi do szczęścia. To szczęście jest drogą."</strong>
                        </div>
                        <br />
                        <div align="right"><em>Budda Siakjamuni</em></div>
                    </td>
                </tr>
            </tbody>
        </table>
        <div align="center">
            <hr width="50%"></hr>
            © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
        </div>
    </body>
</html>