<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tr>
                <th style="background-image:url('graf/linia1.jpg')"></th>
                <th scope="col">
                    <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                </th>
                <th style="background-image:url('graf/linia1.jpg')"></th>
            </tr>
            <tr>
                <th width="40%" scope="col"></th>
                <th width="800" scope="col">
                    <div align="left">
                        <img src="graf/osrodek1.jpg" width="397" height="28" align="top" />
                    </div>
                </th>
                <th width="40%" scope="col"></th>
            </tr>
        </table>
        <table class="content" align="center" >
            <tr>
                <td class="styl24 top-left-menu">
                    <img src="graf/start1.gif" alt="Start" class="start-gif"/>
                    <ul class="styl42">
                        <li><a href="index.phtml">główna</a></li>
                        <li><a href="buddyzm.phtml">buddyzm</a></li>
                        <li><a href="wydarzenia.phtml">aktualności</a></li>
                        <li><a href="kontakt.phtml">kontakt</a></li>
                        <li><a href="linki.phtml">linki</a></li>
                    </ul>
                </td>
                <td rowspan="2" class="center-field">
                    <span class="styl43"><br />
                        <br />
                        <br />
                        <br />
                        <h2 align="center">Kontakt</h2>
                        <br />
                        <div align="center">Adres ośrodka:<br />
                            ul.Legionowa 11/132<br />
                            15-281 Białystok<br /><a href="mapa.phtml">(mapa)</a><br /><br />
                            <table width="0" border="0">
                                <tr>
                                    <td>
                                        <p class="styl43">tel.&nbsp;&nbsp;<br/>&nbsp;</p>
                                    </td>
                                    <td>
                                        <p class="styl43">503 737 130 &nbsp;&nbsp;<br />
                                            721 958 121&nbsp;&nbsp;</p>
                                    </td>
                                    <td>
                                        <p class="styl43">- Karol <br />
                                            - Szymon </p>
                                    </td>
                                </tr>
                            </table>
                            <br />
                            <a href="mailto:Bialystok@diamondway-center.org">e-mail: Bialystok@diamondway-center.org</a><br /><br /><br />
                            Bank Ochrony Środowiska 18 1540 1216 2054 4458 2638 0001
                        </div>
                    </span>
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <div align="right"> 
                        <a href="http://www.karmapa.pl/16karmapa/index.htm" onmouseover='karmapa.src = "graf/1g.jpg"' 
                           onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                            <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" />
                        </a>
                        <a href="http://www.karmapa.pl/" onmouseover='trinlej.src = "graf/2g.jpg"' 
                           onmouseout='trinlej.src = "graf/2.jpg"' target="_blank"><img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" />
                        </a>
                        <a href="http://www.lama-ole.pl/" onmouseover='ole.src = "graf/3g.jpg"' 
                           onmouseout='ole.src = "graf/3.jpg"' target="_blank"><img name="ole" src="graf/3.jpg" alt="tekst alternatywny" />
                        </a>
                    </div> 
                </td>
            </tr>
        </table>
        <div align="center">
            <hr width="50%"></hr>
            © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
        </div>
    </body>
</html>
