<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tr>
                <th style="background-image:url('graf/linia1.jpg')"></th>
                <th scope="col">
                    <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                </th>
                <th style="background-image:url('graf/linia1.jpg')"></th>
            </tr>
            <tr>
                <th width="40%" scope="col"></th>
                <th width="800" scope="col">
                    <div align="left">
                        <img src="graf/osrodek1.jpg" width="397" height="28" align="top" />
                    </div>
                </th>
                <th width="40%" scope="col"></th>
            </tr>
        </table>
        <table class="content"align="center">
            <tr>
                <td class="top-left-menu styl24">
                    <img src="graf/start1.gif" alt="Start" class="start-gif" />
                    <ul class="styl42">
                        <li><a href="index.phtml">główna</a></li>
                        <li><a href="buddyzm.phtml">buddyzm</a></li>
                        <li><a href="wydarzenia.phtml">aktualności</a></li>
                        <li><a href="kontakt.phtml">kontakt</a></li>
                        <li><a href="linki.phtml">linki</a></li>
                    </ul>
                </td>
                <td rowspan="2" class="center-field">
                    <div class="styl43"><br />
                        <h2 align="center">Linki</h2>
                        <ul type="disc">
                            <li><a href="http://www.buddyzm.pl/" target="_blank">http://www.buddyzm.pl/</a></li><br />
                            <li><a href="http://www.diamentowadroga.pl/" target="_blank">http://www.diamentowadroga.pl/</a></li><br />
                            <li><a href="http://www.fsh.pl/" target="_blank">http://www.fsh.pl/</a></li><br />
                            <li><a href="http://klub108.buddyzm.pl/" target="_blank">http://klub108.buddyzm.pl/</a></li><br />
                            <li><a href="http://www.stupahouse.pl/" target="_blank">http://www.stupahouse.pl/</a></li><br />
                            <li><a href="http://www.europe-center.org/" target="_blank">http://www.europe-center.org/</a></li><br />
                            <li><a href="http://www.karmapa.org/" target="_blank">http://www.karmapa.org/</a></li><br />
                            <li><a href="http://www.lama-ole-nydahl.org/" target="_blank">http://www.lama-ole-nydahl.org/</a></li><br />
                            <li><a href="http://www.diamondway-buddhism.org/" target="_blank">http://www.diamondway-buddhism.org/</a></li><br />
                            <li><a href="http://www.diamondway-teachings.org/" target="_blank">http://www.diamondway-teachings.org/</a></li><br />
                        </ul>
                    </div>
                </td>
            </tr>
            <tr>
                <td valign="top">
                    <div align="right"> 
                        <a href="http://www.karmapa.pl/16karmapa/index.htm" onmouseover='karmapa.src = "graf/1g.jpg"' 
                           onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                            <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" /></a>

                        <a href="http://www.karmapa.pl/" onmouseover='trinlej.src = "graf/2g.jpg"' 
                           onmouseout='trinlej.src = "graf/2.jpg"' target="_blank"><img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" /></a>

                        <a href="http://www.lama-ole.pl/" onmouseover='ole.src = "graf/3g.jpg"' 
                           onmouseout='ole.src = "graf/3.jpg"' target="_blank"><img name="ole" src="graf/3.jpg" alt="tekst alternatywny" /></a>
                    </div> 
                </td>
            </tr>
        </table>
        <div align="center">
            <hr width="50%"></hr>
            © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
        </div>
    </body>
</html>
