<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tr>
                <th style="background-image:url('graf/linia1.jpg')"></th>
                <th scope="col">
                    <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                </th>
                <th style="background-image:url('graf/linia1.jpg')"></th>
            </tr>
            <tr>
                <th width="40%" scope="col"></th>
                <th width="800" scope="col">
                    <div align="left">
                        <img src="graf/osrodek1.jpg" width="397" height="28" align="top" />
                    </div>
                </th>
                <th width="40%" scope="col"></th>
            </tr>
        </table>
        <table class="content" align="center">
            <tr>
                <td class="styl24 top-left-menu">
                    <img src="graf/start1.gif" alt="Start" class="start-gif" />
                    <ul class="styl42">
                        <li><a href="index.phtml">główna</a></li>
                        <li><a href="buddyzm.phtml">buddyzm</a></li>
                        <li><a href="wydarzenia.phtml">aktualności</a></li>
                        <li><a href="kontakt.phtml">kontakt</a></li>
                        <li><a href="linki.phtml">linki</a></li>
                    </ul>
                </td>
                <td rowspan="2" class="center-field" style="padding-top: 5px; padding-left: 6px;">
                    <!--  <iframe
                                                src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=bia%C5%82ystok,+waszyngtona+22&amp;sll=37.0625,-95.677068&amp;sspn=36.368578,65.830078&amp;ie=UTF8&amp;hq=&amp;hnear=Jerzego+Waszyngtona+22,+Bia%C5%82ystok,+Podlaskie,+Polska&amp;ll=53.130088,23.156004&amp;spn=0.018024,0.036478&amp;z=14&amp;output=embed">
                                                </iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=pl&amp;geocode=&amp;q=bia%C5%82ystok,+waszyngtona+22&amp;sll=37.0625,-95.677068&amp;sspn=36.368578,65.830078&amp;ie=UTF8&amp;hq=&amp;hnear=Jerzego+Waszyngtona+22/19,+Bia%C5%82ystok,+Podlaskie,+Polska&amp;ll=53.130088,23.156004&amp;spn=0.018024,0.036478&amp;z=14" style="color:#0000FF;text-align:left"></a></small>
                                                </iframe>
                    -->
                 <!--    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2394.5910915964814!2d23.221672700000013!3d53.11753410000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ffed0d0c2e6c9%3A0x389eb5ee3e3a99e6!2sPozioma+63%2C+15-558+Bia%C5%82ystok!5e0!3m2!1sen!2spl!4v1423686268920"  width="577" height="464" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" ></iframe> -->
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2394.022236554954!2d23.155102000000007!3d53.127746400000014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ffc069ef5e39b%3A0xbe11b6cbec73a60a!2sLegionowa+11%2C+Bia%C5%82ystok!5e0!3m2!1sen!2spl!4v1438761064834" width="577" height="464" frameborder="0" style="border:0" allowfullscreen></iframe>

                </td>
            </tr>
            <tr>
                <td valign="top">
                    <div align="right">
                        <a href="http://www.karmapa.pl/16karmapa/index.htm" onmouseover='karmapa.src = "graf/1g.jpg"'
                        onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                        <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" /></a>
                        <a href="http://www.karmapa.pl/" onmouseover='trinlej.src = "graf/2g.jpg"'
                        onmouseout='trinlej.src = "graf/2.jpg"' target="_blank">
                        <img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" /></a>
                        <a href="http://www.lama-ole.pl/" onmouseover='ole.src = "graf/3g.jpg"'
                        onmouseout='ole.src = "graf/3.jpg"' target="_blank">
                        <img name="ole" src="graf/3.jpg" alt="tekst alternatywny" /></a>
                    </div>
                </td>
            </tr>
        </table>
        <div align="center">
            <hr width="50%"></hr>
            © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
        </div>
    </body>
</html>