<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <?php require 'layout/head.phtml'; ?>
    <body>
        <table class="top-line">
            <tbody>
                <tr>
                    <th style="background-image:url('graf/linia1.jpg')"></th>
                    <th scope="col">
                        <img src="graf/logo1.jpg" height="50" width="800" alt="kagyu"/>
                    </th>
                    <th style="background-image:url('graf/linia1.jpg')"></th>
                </tr>
                <tr>
                    <th scope="col" width="40%"></th>
                    <th scope="col" width="800">
                        <div align="left"><img src="graf/osrodek1.jpg" align="top" height="28" width="397" /></div>
                    </th>
                    <th scope="col" width="40%"></th>
                </tr>
            </tbody>
        </table>
        <table class="content" align="center" >
            <td class="styl24 top-left-menu">
                <img src="graf/start1.gif" alt="Start" class="start-gif" />
                <ul class="styl42">
                    <li><a href="index.phtml">główna</a></li>
                    <li><a href="buddyzm.phtml">buddyzm</a></li>
                    <li><a href="wydarzenia.phtml">aktualności</a></li>
                    <li><a href="kontakt.phtml">kontakt</a></li>
                    <li><a href="linki.phtml">linki</a></li>
                </ul>
            </td>
            <td rowspan="2" class="center-field">
                 <div align="center">
                <h2>Wykład Tadeusza Uchto, 19 lutego 2016</h2>
                <h3>Serdecznie zapraszamy na wykład Tadeusza Uchto, polskiego nauczyciela buddyzmu.</h3>
                <h4>Tadeusz Uchto – praktykę buddyzmu Diamentowej Drogi rozpoczął po spotkaniu Lamy Ole w 1983. Po 4 latach praktyki został poproszony przez Lamę Ole o nauczanie buddyzmu. Tadeusz jest doświadczonym nauczycielem. Przez lata dawał wykłady o tematyce buddyjskiej w Polsce i za granicą oraz prowadził kursy medytacyjne, między innymi Niungne. Zawodowo zajmuje się medycyną niekonwencjonalną. Na co dzień mieszka i pracuje w Poznaniu.
                <p>Wykład ma charakter otwarty. Zapraszamy wszystkich zainteresowanych.</p>
                <p>Wstęp wolny.</p>
                </h4>
                <p>
                <strong>Kiedy:</strong> 19 lutego, piątek
                </p>
                <p>
                <strong>Godzina:</strong> 19.00
                </p>
                <p>
                <strong>Temat:</strong> "Wyjaśnienia do medytacji XVI Karmapy"
                </p>
                <p>
                <strong>Miejsce:</strong> BOM Białystok Legionowa 11/132
                <br/>
                </p>
                <br/>
                <p>tel. 503 737 130 - Karol</p>
                <p>tel. 721 958 121 - Szymon</p>
                <br/>
                <p>
                <strong>Serdecznie zapraszamy :)</strong>
                </p>
            </div>
                <tr>
                    <td valign="top">
                        <div align="right">
                            <a href="http://www.karmapa.pl/16karmapa/index.htm" onmouseover='karmapa.src = "graf/1g.jpg"'
                            onmouseout='karmapa.src = "graf/1.jpg"' target="_blank">
                            <img src="graf/1.jpg" name="karmapa" alt="tekst alternatywny" />
                            </a>
                            <a href="http://www.karmapa.pl/" onmouseover='trinlej.src = "graf/2g.jpg"'
                            onmouseout='trinlej.src = "graf/2.jpg"' target="_blank"><img name="trinlej" src="graf/2.jpg" alt="tekst alternatywny" />
                            </a>
                            <a href="http://www.lama-ole.pl/" onmouseover='ole.src = "graf/3g.jpg"'
                            onmouseout='ole.src = "graf/3.jpg"' target="_blank"><img name="ole" src="graf/3.jpg" alt="tekst alternatywny" />
                            </a>
                        </div>
                    </td>
                </tr>
            </div>
        </td>
    </table>
    <div align="center">
        <hr width="50%"></hr>
        © Ośrodek Medytacyjny Buddyjskiego Związku Diamentowej Drogi Linii Karma Kagyu w Białymstoku
    </div>
</body>
</html>