<head>
    <title>Buddyzm Diamentowej Drogi / Białystok</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="Description" content="Buddyzm Diamentowej Drogi - Ośrodek w Białymstoku" />
    <meta name="Keywords" content="buddyzm, Białystok, Kagyu, buddyjski, ośrodek,
          medytacja, Budda, Karmapa, Dharma, nirwana, samsara, mantra, diamentowa,
          droga, Tybet, buddyjskie, buddyjska, buddyzmowi, buddyzmem, buddyzmie,
          buddyjskich, sangha, medytacje, Lama Ole Nydahl, związek buddyjski" />
    <meta name="robots" content="index, follow" />
    <link rel="shortcut icon" href="graf/favicon.ico" ></link>
    <link rel="stylesheet" href="css/style.css" type="text/css"></link>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48221209-2', 'bialystok.buddyzm.pl');
  ga('send', 'pageview');

</script>
</head>
